---
title: "Undermind.ai est-il adapté pour découvrir des études en histoire ?"
format: html
author:
      - name: "Pascal Martinolli"
        orcid: "0000-0003-0122-5300"
date: "2026-07-06"
categories: [HumanitésNumériques, histoire]
description: "Où l'on explore l'outil de découverte Undermind pour la recherche d'études en histoire qui utilise de l'IA générative, principalement à travers des agents de recherche et de traitement. On en profite pour affûter une démarche critique vis-à-vis de ces nouvelles méthodes de travail de la documentation."
---

## Introduction

Undermind.ai est un outil de découverte de littérature scientifique utilisant l'IA générative (IAgen) auquel les Bibliothèques de l'Université de Montréal se sont abonnées pour un an (avec les outils Consensus.app et LeapSpace). Voici quelques tests, suggestions et commentaires sur Undermind pour le domaine de la recherche en histoire.

## Corpus

Undermind.ai utilise principalement le corpus de [Semantic Scholar](https://www.semanticscholar.org/), soit plus de [200](https://www.semanticscholar.org/product) millions d'études (articles de revues principalement). Cet index est géré par *The Allen Institute for Artificial Intelligence ([Ai2](https://allenai.org/))* qui fait des efforts pour diffuser en code source ouvert la plupart de ses projets.

Semantic Scholar a été conçu à l'origine pour l'informatique, la biomédecine, les neuroscience, etc. Depuis 2024-2025 environ, il a intégré des éditeurs en sciences humaines et sociales et il est ainsi devenu très intéressant pour les humanités. Par exemple, il contient les notices de ces [maisons d'édition](https://www.semanticscholar.org/about/publishers) ou bases de données bibliographiques :

- Cambridge University Press

- De Gruyter (+Brill)

- HAL

- Project Muse

- Sage Publishing

- Science

- Springer Nature

- Taylor & Francis

- The MIT Press

- The Royal Society Publishing

- The University of Chicago Press

- Wiley

- etc. Il y en a d'autres. Je n'ai listé ci-dessus que celles qui contiennent de la documentation en histoire.

### Place de l'histoire dans Semantic Scholar

Selon [cet article](https://doi.org/10.1515/bfp-2023-0057) daté, Semantic Scholar ne contiendrait que 34 386 études en histoire (dont 33,24% en libre accès), soit 0.13% du corpus total. **Cependant**, cet article se base sur des données de 2008 à 2020 et les maisons d'édition contenant des études historiques ont été rajoutées par la suite.

Pour refaire une estimation, j'ai fait une recherche simple avec le mot-clé *history* et le filtre par Domaine d'étude : Histoire pour obtenir **1,4 millions de résultats** (juillet 2026). En volume, c'est l'équivalent des deux bases de données disciplinaires *Historical Abstracts* et *America History & Life* combinées.

Toutes les périodes historiques semblent couvertes (antique, médiévale, moderne et contemporaine).

### Biais envers l'histoire

Nous avons vu que la **quantité** de références sur l'histoire est minime dans le corpus de Semantic Scholar. Mais ce n'est pas tout, il y a aussi une différence de **qualité** des métadonnées des références qui peut biaiser, ou sous-représenter, ou moins bien repérer les études en histoire.

J'ai mis dans ce tableau les deux extrêmes opposés de la qualité des métadonnées avec les neurosciences (excellentes métadonnées) et l'histoire (métadonnées inégales, hétérogènes, lacunaires).

+--------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Métadonnées en neuroscience                                                          | Métadonnées en histoire                                                                                 |
+======================================================================================+=========================================================================================================+
| 99,9 % contiennent un résumé                                                         | Résumés parcellaires                                                                                    |
+--------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Indexation des principaux articles de revues ou de colloques                         | Peu de livres\                                                                                          |
|                                                                                      | Très peu de chapitres\                                                                                  |
|                                                                                      | Articles de revues                                                                                      |
+--------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Nombreuses données de citation                                                       | Données de citation minimes                                                                             |
+--------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Identifiants pérennes (DOI, ORCID)                                                   | Peu de DOI\                                                                                             |
|                                                                                      | Peu d'ORCID\                                                                                            |
|                                                                                      | ISBN sous-représentés                                                                                   |
+--------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| 99,9& de documents nativement électroniques (meilleure extraction du texte)          | Moins de documents nativement électroniques : imprimés ou pages numérisées avec OCR de qualité variable |
+--------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Peut être plus de publication en ibre accès, permettant un accès au texte intégral ? | Peut être moins de libre accès ?                                                                        |
+--------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Presque exclusivement rédigé en anglais                                              | Nombreuses langues différentes                                                                          |
+--------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+

## Fonctionnement

Les algorithmes de Undermind utilisent GPT 4 qui pilote des agents pour 3 phases :

- **Agent recherche :** raffiner les questions et pour classer les résultats. Selon moi, c'est [l'aspect le plus performant]{.underline} de Undermind. Il permet de repérer des documents souvent inaccessibles avec des opérateurs booléens classiques ([*search resistant concepts*](https://farhadinfo.medium.com/stop-searching-and-you-will-find-it-search-resistant-concepts-in-systematic-searching-c7968ddf22c8)).

- **Agent traitement** : Traiter le contenu des études récupérées en libre accès (ou celles versées par l'utilisateur) : synthétiser le contenu, extraire des informations, les traduire, etc. Cet aspect est un peu plus limité.

- **Agent rédaction** : Rédiger du texte. Cet aspect est aussi limité. Je préfère copier-coller les résultats des échanges avec l'agent de traitement plutôt que de les faire rédiger. En effet, c'est très lent et surtout il peut y avoir des pertes d'information entre le traitement et la rédaction.

Allons dans les détails de l'Agent recherche et l'Agent traitement.

### Agent recherche

- La recherche utilise des opérateurs **booléens** classiques, une recherche **sémantique** (puissante) et une exploration des liens de **citations** quand ceux-ci sont disponibles.

  - L'algorithme de **sélection**, de tri et de classement est aussi très efficace. C'est la garantie que les résultats trouvés sont peu nombreux (souvent une centaine ou moins) et pertinents.

- Undermind utilise **seulement le titre et le résumé** pour repérer des documents. Une fois les résultats affichés, il est possible de lancer l'Agent de traitement dans le texte intégral quand celui-ci est disponible.

- Si on lance la recherche en français ou en anglais, les résultats peuvent varier.

- De manière générale, les outils IA génératifs gèrent mal la négation (NOT ou "je ne veux pas de choses sur ..."). À éviter.

- Pour lancer la recherche, il faut se limiter aux mots-clés thématiques et ne pas utiliser des auteurs, des noms de revues, etc.

- Lancer plusieurs recherches dans un même projet avec différents angles pour augmenter l’ensemble des *All papers*.

  - Lancer des requêtes génériques exploratoire et ensuite lancer de nombreuses requêtes spécifiques avec du vocabulaire adapté et spécifique pour développer des sous-sujets.

  - Avancé : Comme il n'y a pas de possibilité de supprimer des documents de *All papers* (et de virer les faux positifs) : Mettre sa sélection de documents dans *Starred* puis lancer un Agent traitement sur cette vue.

### Agent traitement : suggestions de demandes

Une fois les recherches terminées, voici quelques suggestions à lancer avec l'agent conversationnel de Undermind.

#### Échanger sur les méthodes de travail

- Fiabilité = bonne

- Raisons = Ancré dans les résultats et augmenté par le modèle de langue • Interactivité raisonnée

- « Créer une grille de lecture pour classer les études selon la question centrale pour distinguer les études à garder au centre de la synthèse, celles à garder en appui, et celles à rejeter. • Quelles études lire en premier ? Rédiger un parcours des études les plus simples/générales aux études les plus avancées/spécifiques. Avec quel angle en tête ? • Lister les principaux concepts et les principales méthodes utilisés dans ces études et que je dois maîtriser. • Extraire les idées principales d’une seule étude en texte intégral avec sa \[cle00\] • Comparer deux études en texte intégral chacune. »

#### Demander des analyses externes des documents

- Fiabilité = moyenne

- Raisons = Couverture imparfaite du domaine • Métadonnées inégales

- « Quel est le papier le plus cité ? • Quels sont les auteurs ou les équipes qui reviennent le plus souvent ? • Quelles sont les sources de financement des études ? • Quels sont les enjeux inter ou multidisciplinaires ? »

#### Synthèse globale du sujet avec l’ensemble des documents

- Fiabilité = moyenne [voire basse]{.underline}

- Raisons = Couverture imparfaite du domaine • Certains documents ne sont accessibles qu’en titre résumé • Extraction imparfaite

- « Sur quels points la plupart des experts sont d’accord ? Et sur quels points ils ne sont pas d’accord • Quelles sont les principales limites des études ? • Quelles sont les résultats les plus robustes ? • Quels sont les aspects les plus/moins explorés ? • Quelles seraient les questions de recherche les plus prometteuses ? • Est ce que l’ensemble des documents repérés fait le tour de la question ? »

#### Exemple de flux de travail

1.  Lancer une ou plusieurs recherches sur un sujet.

2.  Aller dans *All papers.*

3.  Demander à l'agent conversationnel : « Extrait à partir des documents tous les concepts et toutes les méthodes importantes à maîtriser pour étudier ce sujet. »

4.  Une fois la liste des concepts et méthodes produites, demander : « Trouve des articles scientifiques pouvant servir de revues générales, d'introduction ou de synthèses conceptuelles pour introduire les concepts, les cadres méthodologiques et les notions nécessaires à la lecture de la littérature sur mon sujet. Privilégie les études historiographiques. »

5.  Terminer en demandant : « Donne-moi des pistes pour aller chercher de l'information en dehors de Undermind. »

### Astuces (*hacks*)

- Même si Undermind n'a pas été conçu pour cela, il est possible de demander via le moteur GPT4 de faire des actions non-prévues ou hors du strict cadre recherche-traitement-rédaction :

  - Traduire du texte

  - Créer du code informatique simple

  - Lancer une recherche sur le web

  - etc.

## Avantages des outils AIgen

Permet de réduire la « friction » des chercheurs débutants avec les outils de recherche :

- Lancer des recherches sans connaître de langage d'interrogation.

- Ne pas avoir trop de résultats à évaluer.

- Intéragir « avec plaisance » avec l'outil.

- Pointer les parties pertinentes d'une étude si le texte intégral est disponible : on peut vérifier ou rejeter une étude plus rapidement.

Bref, toutes les fonctionnalités qui permettent de pousser vers les sources et de mieux les traiter sont pertinentes.

## Problèmes généraux de tous les outils IAgen 

À garder à l'esprit pour tous les outils qui contiennent des fonctions IA génératives.

### Limites de nature

Par leur nature conversationnelle, ces types d'outils peuvent garder l'engagement de l'utilisateur à l'intérieur de l'outil sans les pousser vers les sources (ce problème de méthode de travail n'est pas unique à Undermind). Exemples :

- Ne pas lancer d'autres recherches dans d'autres outils plus exigeants ou méconnus, parce que la recherche dans Undermind semble suffire.

- Ne pas suivre les liens de citation dans les sources repérées, pour découvrir de nouveaux documents.

- Ne pas passer par des types de documents plus adaptés pour la question de recherche car Undermind contient presque uniquement des articles (peu de chapitres). Par exemple : des articles d'encyclopédie spécialisées ou d'ouvrages de références, des livres spécialisés, etc.

- Demander à l'outil d'utiliser les documents repérés pour directement produire un texte synthétique sans lire les sources.

- Demander à l'outil d'extraire les idées principales et de les lier ensemble, sans passer par l'absorption personnelle du contenu, lu et compris.

- Ne pas rédiger soi-même l'argumentaire.

Bref, toutes les fonctionnalités qui font « travailler hors-sol » sans aller vers les sources sont à rejeter.

### Limites de fonctionnement

- Effet « boîte noire » : même si les données de Semantic Scholar sont ouvertes, nous n'avons pas accès aux algorithmes de Undermind pour des raisons de concurrence commerciale intense. Cette non-transparence est éloignée de la reproductibilité scientifique.

- Effet « [Eliza](https://fr.wikipedia.org/wiki/Effet_ELIZA) » : on attribue des pensées humaines (donc de processus mentaux logiques) à ces outils alors qu'ils sont essentiellement basés sur des règles syntaxiques et non logique/factuel. On peut aussi leur attribuer une sur-compétence.

- Parmi les algorithmes utilisés, ceux qui utilisent de l'IA générative ont une capacité de traitement limité ce qui fait un possible goulet d'étranglement invisible à l'utilisateur.

### Délestage de compétences de base ?

- Lorsque l'on fait une recherche de documents, on prend une multitude de décisions et on exerce sa mémoire et son jugement en alternance et progressivement. Ces processus mentaux produisent de l'apprentissage. Un outil qui se pose en intermédiaire facilitateur et prestataire de service et dont on connaît mal le fonctionnement peut réduire ces apprentissages. Exemples :

  - Habileté à transcrire une demande d’information en mots-clés, à évaluer la qualité de la demande et à reformuler sa stratégie de recherche.

  - Habileté à évaluer les résultats d’une recherche (avec les outils IAg c’est toujours une petite sélection de résultats dont on ne connaît pas les critères)

  - Habileté à prendre la décision de sélectionner un résultat pertinent (les résultats sont présentés et rédigés dans un langage assertif ou d’autorité, où l’outil se substitue au jugement de l’utilisateur).

  - Habileté à se construire une image mentale de l’ensemble de la documentation scientifique sur un sujet et comment la conversation scientifique s’articule entre ceux-ci.

  - Habileté à évaluer et extraire l’information pertinente pour soutenir son argumentation.

  - Habileté à repérer le niveau d’exhaustivité atteint lors d’une recherche d’information.

- Surévaluation de la qualité des résultats :

  - « Je n'ai pas besoin de chercher plus, ou de chercher ailleurs, ou de chercher différemment. »

  - « Je n'ai pas besoin de vérifier que la source dit bien ce qui est extrait. »

  - etc.

## Quelques solutions et postures

- Former aux biais induits par ces méthodes de recherche documentaires nouvelles.

  - Avoir une démarche d'auto-réflexion sur ses apprentissages.

  - Interroger ses propres biais pro- ou anti-IA pour la recherche documentaire.

- Demander à Undermind d'étendre ses métadonnées à plus de notices sur l'histoire (surtout pour les livres). Pour l'instant, de tous les outils de ce type que j'ai testé, Undermind est celui qui a le mieux fonctionné pour les humanités.

## Réflexions sur l'IA générative et l'histoire

- Par nature, les algorithmes génératifs applatissent les nuances, les aspérités, les achoppements, etc. Or faire de l'histoire, n'est-ce pas de les repérer, de les comparer, de les contextualiser, de les analyser et de les restituer dans un argumentaire ?

  - Les outils évoluent vite : l'an passé mon exemple favori pour montrer les erreurs de l'IAgen était de demander régulièrement : « Est-ce que Harry Truman est le décideur final du bombardement de Hiroshima et de Nagazaki ? » Jusqu'à mai 2026, les réponses ont toujours été décevantes. Depuis peu, elles sont plus nuancées et proches du « [consensus](https://amzn.to/4pRq5k8) » historique sur la question.

- Les outils IA peuvent être des outils bloqués sur la [lecture distante](https://hal.science/hal-03152747v1). Il faut les forcer à faire de la « [lecture télescopique](https://skhole.ecrituresnumeriques.ca/episodes/ep10_aledavood/) » pour se rapprocher des sources.

- Les outils spécialisés comme Undermind sont intéressants à comparer avec d'autres outils semblables de la même famille (Consensus.app, LeapSpace, Elicit, SciSpace, etc.). Il faudrait aussi les comparer avec des outils généralistes de dernière génération comme Claude et ChatGPT qui commencent à intégrer des agents et des interrogations de bases de données avec le protocole MCP. À suivre...

------------------------------------------------------------------------

## Annexe

- Les test, les explorations et les recommandations ont été faites par moi entre avril et juillet 20026. Ils ont été supplémentés par des lectures des tests de [Aaron Tay](https://aarontay.substack.com/) et du [papier](https://www.undermind.ai/whitepaper.pdf) (biaisé) de Undermind sur le sujet.
- Sur le pilotage d'agents IA, Philippe Rygiel en discute dans cette [prépublication](https://inria.hal.science/hal-05673494v1). Il aborde d'autres enjeux sur les technologies « IA » pour l'histoire (OCR, HTR, LLM, etc.)
- Pascal Martinolli. 2025. **“Bingo critique de l’IAg pour la recherche de documents”**. <https://boite-outils.bib.umontreal.ca/ld.php?content_id=37726345>.
  - Idéal pour affûter ses critiques lorsqu'on teste un outil IA génératif.
- ———. 2025. **“Test d’outils IAg génératives pour la recherche universitaire”**. <https://boite-outils.bib.umontreal.ca/ld.php?content_id=37640268>.
  - Un peu daté maintenant mais listant la plupart des outils de repérage de documents en libre accès ou en accès freemium.
