---
title: "Construire un indicateur bibliométrique pour l'histoire avec les comptes-rendus de lecture"
format: html
author: "Pascal Martinolli"
date: "2026-02-25"
categories: [HumanitésNumériques, histoire, Zotero]
description: "Où l'on construit notre propre indicateur bibliométrique pour valoriser la production scientifique en histoire via les livres avec un protocole simple de collecte, de traitement et de présentation des comptes-rendus de lecture."
---

## Importance des comptes-rendus en histoire

Les comptes-rendus de lecture sont un type de publication scientifique important pour la recherche historique. Par exemple, pour la célèbre revue des *Annales d'histoire économique et sociale*, fondée en 1929 par Marc Bloch et Lucien Febvre, elle permet non seulement de sélectionner les meilleurs ouvrages publiés mais surtout elle permet de **prolonger la conversation scientifique** critique sur le sujet traité. Ce format soutient la méthodologie « histoire-problème », théorisée par les *Annales*, qui vise à remplacer l'histoire événementielle par une analyse centrée sur des questions précises posées au passé (Müller 1997).

> « Une large place est également accordée, dans les pages de la revue, à l’examen et à la critique de la production scientifique récente sous forme de comptes rendus et d’analyses approfondies d’ouvrages marquants, à travers des notes critiques et des forums. » ([source](https://annales.ehess.fr/)) (écouter aussi [Paroles d'histoire](https://youtu.be/KkIR6yovndo?t=2440) à 00:40:00).

## Invisibilité des comptes-rendus

Les comptes-rendus de lecture sont relativement **peu ou mal valorisés** dans les bases de données bibliographiques. Déjà sous la forme de papier, il était difficile d'identifier quel livre avait été critiqué et commenté. Cela ne s'est pas amélioré avec le passage à l'électronique. Certaines bases de données excluent ce type de document (Pubmed, PsychINFO, etc.).

Souvent pour les comptes-rendus, leur indexation des **métadonnées est très médiocre.** Par exemple, il est courant que la référence bibliographique complète du livre se retrouve intégralement dans le champ `Titre`. De plus, dans ce champ Titre, la référence est présentée dans un style bibliographique aléatoire, parfois avec des problèmes d'accentuation, ou des balises HTML mal encodées, parfois avec le prix ou le format, etc.

Exemple :

> JAENEN, Cornelius J., *The Role of the Church in New France*. The Frontenac Library, 7. Toronto, Montréal, McGraw-Hill Ryerson \[c1976\]. x-182 p. \$5.95 broché, ISBN 0-07-082258-1. \$6.95

Dans mes formations, j'ai remarqué que les étudiants débutants pensent qu'en cliquant sur cette référence bibliographique ils vont accéder au livre. Dans la référence de l'exemple ci-dessus, j'apprécie la démarche pédagogique de *Érudit* qui [explique](https://doi.org/10.7202/303593ar) « Ce document est le compte rendu d'une autre oeuvre tel qu'un livre ou un film. L'oeuvre originale discutée ici n'est pas disponible sur cette plateforme. » C'est très loin d'être le cas pour les autres bases de données car certaines ne font même pas la différence entre les comptes-rendus et les articles de recherche.

## Indicateurs bibliométriques

Les chercheurs ont de plus en plus besoin de valoriser leur production scientifique. Celle-ci se manifeste principalement par la liste de toutes leurs publications significatives, principalement sous la forme d'articles révisés par les pairs, de chapitres dans des ouvrages collectifs ou sous la forme de monographies.

Un autre volet de valorisation de leur recherche porte sur le rayonnement de leur recherche. Pour cela, de nombreux indicateurs existent : nombre de citations, nombre de mentions médiatiques (*altmetrics*), etc. Or j'ai remarqué que dans ce volet il y avait un grand absent : le **nombre de comptes-rendus de lecture des livres publiés par les chercheurs**. Cela est probablement dû au fait que ce type de document n'est important que pour la discipline de l'histoire et des disciplines annexes (histoire de l'art, etc.).

Je pense que passer à côté de cette dimension est dommageable pour la valorisation de la recherche en histoire. Voici donc un protocole pour recenser, collectionner et présenter ces données.

## Recenser les comptes-rendus

Établir une liste de bases de données et de plateformes à interroger pour chercher des comptes-rendus de lecture. Cette liste devrait contenir au moins :

- Ces bases de données généralistes :
  - [*Google Scholar*](https://scholar.google.com/)
  - [*OpenAlex*](https://openalex.org/)
  - [*JSTOR*](https://www.jstor.org/)
  - [*Dimensions*](https://app.dimensions.ai/discover/publication)
- Et toutes les bases de données bibliographiques disciplinaires :
  - *Historical Abstracts*
  - *America : History & Life*
  - etc.

Pour aller plus loin et faire un travail avancé de recherche bibliographique, on pourrait aussi chercher dans :

- D'autres bases de données ou plateformes :
  - dans d'autres disciplines
  - *Web of Science*
  - [Isidore](https://isidore.science/) *(*contient *[OpenEdition](https://www.openedition.org/))*
  - tout *ProQuest*
  - tout *EBSCO*
  - tout [Érudit](https://www.erudit.org/)
  - tout [CAIRN](https://shs.cairn.info/)
  - tout [Persée](https://www.persee.fr/),
  - etc.
- Des périodiques spécialisés dans les comptes-rendus de lecture :
  - [*Choice Reviews*](https://www.choicereviews.org/)
  - [*APA PsycCritiques*](https://www.apa.org/pubs/databases/psyccritiques)
  - [*New York Book Review*](https://www.nybooks.com/)
  - [*London Review of Books*](https://www.lrb.co.uk/)
  - [*The Times Literary Supplement*](https://www.the-tls.com/)
  - [*Los Angeles Review of Books*](https://lareviewofbooks.org/)
  - etc.
- Des comptes-rendus de livres dans des périodiques généralistes :
  - [*Harpers*](https://harpers.org/)
  - [*The Atlantic*](https://www.theatlantic.com/)
  - [*The New Yorker*](https://www.newyorker.com/)
  - [Le Monde des livres](https://www.lemonde.fr/livres/)
  - etc.

Pour chaque outil choisi, chercher uniquement dans le champ `Titre/Title` avec le nom du chercheur sous la forme `Prénom Nom` ou sous la forme `"Prénom Nom"`. Notez que certains outils ont des subtilités d'utilisation et que celles-ci peuvent changer d'une année à l'autre. À vous de développer votre expertise des outils et de noter les bonnes pratiques dans un document dédié.

## Collectionner les comptes-rendus

Collecter toutes les références aux comptes-rendus dans Zotero. Pour cela :

1.  Créer une collection nommée `Prénom Nom` du chercheur.
2.  Créer une sous-collection pour chaque outil interrogé, nommé avec le nom de l'outil.
3.  Verser les comptes-rendus dans les collections correspondantes.
4.  Quand la récolte est terminée, dédoublonner les comptes-rendus avec le plugin [Zoplicate](https://github.com/ChenglongMa/zoplicate) (qui fait ça mieux que les fonctions de dédoublonnage de base de Zotero).
    - Fusionner les doublons avec Zoplicate/Doublons.
    - Fusionner manuellement les doublons restants (car il va en rester). Pour cela, il faut trier les colonnes de Zotero par Année, puis par Créateur, puis par Publication. Clic-droit \> Fusionner les documents.

## Présenter les données

Une manière simple de présenter les résultats de l'investigation bibliométrique est de rédiger un court paragraphe expliquant l'importance des comptes-rendus de lecture et de décrire l'impression générale de l'investigation. Ensuite, lister les revues par ordre descendant de *Journal Impact Factor* (JIF), suivi par le nombre de comptes-rendus entre parenthèses et le JIF. Pour quelques revues avec un haut JIF : les mettre en gras ou avec un astérisque avec une légende expliquant ce marquage. Il est aussi possible d'ajouter un tableau avec le nombre de comptes-rendus par année de publication.

### Exemple

> Selon des recherches dans les deux principales bases de données en histoire (*America : History & Life* et *Historical Abstracts*) et avec des outils généralistes comme *OpenAlex*, *Google Scholar* et *JSTOR*, **vos livres ont été commentés dans au moins 28 comptes-rendus de lecture publiés dans des revues révisées par les pairs** et 5 comptes-rendus dans des journaux ou magazines influents. Les comptes-rendus sont un type de publication important pour la conversation scientifique en histoire. Ces comptes-rendus proviennent de revues importantes en histoire. Le *Journal Impact Factor* (JIF), indiqué dans le tableau ci-dessous, ne dit rien de la qualité des comptes-rendus car c'est un indicateur d'impact générique de la revue.
>
> |  |  |  |
> |---------------------------------|-------------------|--------------------|
> | *Revue* | *JIF* | *Nb de comptes-rendus* |
> | **American Historical Review** | **1.2** | **2** |
> | **British Journal for the History of Science** | **1.2** | **1** |
> | **Isis** | **0.9** | **4** |
> | **History of Science** | **0.8** | **1** |
> | History of European Ideas | 0.5 | 1 |
> | Intellectual History Review | 0.5 | 1 |
> | History & Memory | 0.3 | 3 |
> | ... autres revues à comité de lecture |  | 15 |
> | ... journaux et magazines influents |  | 5 |

On peut également souligner la diversité des revues dans lesquelles les comptes-rendus sont publiés, ainsi que la variété des institutions d'affiliation et des pays d'origine des auteurs de ces comptes-rendus.

## Astuces

Le *Journal Citation Reports* (*JCR*) ne permet pas de verser une liste de revues et de retourner celles-ci avec leur JIF (4 maximum). *SCImago* ne permet pas non plus de le faire en lot (6 maximum; mais avec un indicateur atroce, le h-index, donc à éviter).

Si on fait souvent cette évaluation, il pourrait être judicieux de télécharger les listes des disciplines historiques du JCR et de faire des opérations de réconciliation sur son ordinateur en local.

En cas de non accès au JCR (car il est *paywalled*), je suggère de visiter le site web des revues. En effet, si une revue possède un JIF, alors il y a de grandes chances qu'elle affiche un JIF récent sur son site. Cependant, comme mentionné précédemment, le JIF étant un indicateur d'impact générique de la revue, il ne dit rien de la qualité des contenus pris individuellement (dont les comptes-rendus).

Ne pas utiliser les outils IAg généralistes comme *Claude* ou *ChatGPT* pour récupérer les JIF par revues car 1) cela ne fonctionne pas, et 2) par nature, cela produit des résultats inexacts pour ce type de requête. La construction de cet indicateur est une tâche que l'on veut minutieuse et exacte, donc ne la sabotons pas avec un traitement inadapté.

## Bibliographie

Loez, André. « La fabrique des Annales : épisode 1 ». *Paroles d'histoire*, no. 79/1, 2024. <https://www.youtube.com/watch?v=KkIR6yovndo>

Müller, Bertrand. « Lucien Febvre e la politica della recensione ». *Storiografia*, vol. 1, 1997, 159-176.

------------------------------------------------------------------------

Remerciements pour leurs conseils : Virginie Paquet, Dominic Desaulniers, Laetitia Bracco.
