---
title: "Zotero RDF Viewer : un interface portable pour visualiser une bibliothèque Zotero incorporée dans une page HTML"
author:
      - name: "Pascal Martinolli"
        orcid: "0000-0003-0122-5300"
date: "2026-03-25"
categories: [Zotero, HumanitésNumériques]
description: "Où l'on bricole une page HTML en JavaScript qui visualise une bibliothèque Zotero exportée au format Zotero RDF, intégrée dans la page ou chargée sous forme de fichier. Où l'on produit une sorte de « mini-Kerko » fixe et local pour des besoins simples."
---

## Zotero RDF Viewer

J'ai *vibe codé* un fichier HTML portable qui utilise une exportation Zotero RDF ponctuelle et qui l'affiche avec des facettes dans un navigateur grâce à du JavaScript.

Télécharger ou visualiser [**Zotero RDF Viewer**](https://pmartinolli.github.io/code/zotero-rdf-viewer/) avec environ 300 références RDF embarquées dans la page.

Une autre version customisée avec la base [*academicTTRPG*](https://pmartinolli.github.io/academicTTRPG/) complète, soit plus de 4000 références nettoyées et indexées sur les jeux de rôle sur table. Ça prend du temps à charger mais ça tient la route.

## Utilités

-   Partager une bibliothèque de références Zotero de manière simple.

-   Diffuser des bibliographies de plans de cours, de projets de recherche, de mémoires ou de thèses, etc.

-   Aider au nettoyage des données bibliographiques ou au survol rapide d'une base de données Zotero.

## Fonctionnalités

-   Portable : on a une bibliothèque de références complète et navigable dans un seul fichier HTML, à déposer en ligne ou à utiliser sur son disque dur.

    -   On peut fournir un fichier RDF ou bien avoir des données RDF embarquées dans le code de la page HTML \> Javascript \> dans la constante `DEFAULT_RDF`

-   Je l'ai conçu autour d'un besoin personnel : peu de collections et beaucoup de marqueurs.

    -   Seules les collections qui sont nommées avec un chiffre et un point (comme "1. label" ou "2. titre") sont affichées en facette à gauche. Elles se cumulent avec des AND.

    -   Facettes automatiques sur les types de document. Elles se cumulent avec des OR.

    -   Seuls les marqueurs qui débutent avec un "\_" et un "=" sont affichés dans les facettes à droite. Ordre d'affichage : \_ en majuscules, puis \_ en minuscules, puis =. Elles se cumulent avec des AND.

-   Case de recherche avec troncature à gauche et à droite sur tous les champs.

-   Affichage de la notice bibliographique (presque) complète en déroulé (*collapsible*).

-   Tri par date.

-   Mode jour/nuit.

NB: il y avait des caractères *tick* ' dans les notices bibliographiques. Il m'a fallu les remplacer par des apostrophes dans la base de données Zotero originale et réexporter le tout pour ne pas faire boguer la constante `DEFAULT_RDF` recevant la longue chaîne de caractère en RDF.

## Futurs

-   Ce projet peut servir de base à une analyse quantitative de sa base de références dans le cas d'une revue de littérature (projet à venir, réutilisant les algorithmes de [ZoteroRanalysis](https://github.com/pmartinolli/ZoteroRnalysis)).

-   Développement à explorer : récupérer les données par API.

## Crédits

#### « Mini-Kerko » ? Kézako ?

Je me suis fortement inspiré de l'interface [Kerko](https://whiskyechobravo.github.io/kerko/latest/) pour produire cet outil. Les [Bib/UdeM](https://bib.umontreal.ca/recherche/diffuser/kerko/) et [UQÀM](https://uqam-ca.libguides.com/rayonnement/kerko) ont développé des offres de service autour de cette application conçue par **David Lesieur**. Elle permet de visualiser dynamiquement une bibliothèque partagée Zotero. Le code est superbe. L'application est paramétrable à loisir (facettes pour les collections, etc.). Elle est généreusement offerte en *open source* par son auteur mais... il faut un serveur pour la faire fonctionner, ce qui n'est pas à la portée de tout le monde (moi par exemple).

#### Mais aussi

Je me souviens avoir consulté il y a quelques années une application semblable nommée [Rudolf Geyer Catalog](https://github.com/LWCvL/RudolfGeyerCatalog) par **L.W. Cornelis van Lit**, "The Digital Orientalist". J'avais tenté d'en faire une adaptation pas super fameuse.
